### PR TITLE
Slightly better way to get correct name for actions

### PR DESCRIPTION
**Pull request by nicola-sysdesign**
I found that **get_correct_name(...)** method is a bit convoluted for what it's intended for.
I proposed an simple way to rewrite it but I want some feedback on whether some checks it's needed and what's the better way to handle possible exceptions.

In **refresh_topics_and _actions(...)** I think that it would be slightly better to check if 'goal', 'feedback', ... are present only in the last segment of the topic name.

### CODE REVIEW

**Review by destogl — CHANGES_REQUESTED** [review]
On actions: What are you actually doing here? One splits and joins everything again? Why? Can you please refresh my memory on this?

Other stuff look good.

**Comment by nicola-sysdesign** [comment]
The idea is that to check if a topic_name belong to an action, I only check if the last segment of the topic name is equal to 'goal', 'feedback', 'result', ecc... .
Before it would check the whole topic name and so for example a topic called "/my_**goal**keeper_robot/pose" would be picked as an action.

**Comment by nicola-sysdesign** [comment]
> On actions: What are you actually doing here? One splits and joins everything again? Why? Can you please refresh my memory on 

It only seemed to me a too complex implementation because basically it returns the topic_name without the last segment and None if topic name have only one segment (which subsequently cause an exception).
In my PR that function simply return the topic_name without the last segment.
A check to skip topic names with less than 2 segments can be easily implemented if needed.

**Review by destogl — APPROVED** [review]
Looks good! Thanks!

**Pull request merged**
